# 00. Getting started with Tensorflow: A guide to the fundamentals

[Section Link](https://dev.mrdbourke.com/tensorflow-deep-learning/00_tensorflow_fundamentals/)

This section covers:
- Introduction to tensors;
- Getting information from tensors;
- Manipulating tensors;
- Tensors and numpy;
- Using @tf.function;
- Using GPUs with Tensorflow
- Exercises


## Introduction to Tensors

tensor is a multi-dimensional numeric representation of something. The main difference between tensors and NumPy arrays is that tensors can be used on GPUs and TPUs.



In [1]:
import tensorflow as tf
print(tf.__version__)

2.5.0


### tf.constant

In [3]:
# rank 0 tensor, because it has no dimensions (only a number)
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
scalar.ndim

0

In [5]:
vector = tf.constant([10,10])
vector, vector.ndim

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>, 1)

In [6]:
matrix = tf.constant([[10,7], [7,10]])
matrix, matrix.ndim

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 7, 10]], dtype=int32)>, 2)

In [8]:
another_matrix = tf.constant([[10.,7,],
                              [3.,2.,],
                              [8.,9.]], dtype=tf.float16)
another_matrix, another_matrix.ndim

(<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
 array([[10.,  7.],
        [ 3.,  2.],
        [ 8.,  9.]], dtype=float16)>, 2)

In [13]:
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                     [[13,14,15],
                      [16,17,18]]])
tensor, tensor.ndim

(<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18]]], dtype=int32)>, 3)

### tf.Variable

tensors created with tf.constant are immutable

In [14]:
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [16]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

### Creating random tensors

In [18]:
random_1 = tf.random.Generator.from_seed(42) # set the seed for reproducibility
random_1 = random_1.normal(shape=(3,2)) # create tensor from a normal distribution
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [19]:
random_1 = tf.random.Generator.from_seed(42) # set the seed for reproducibility
random_1 = random_1.normal(shape=(3,2)) # create tensor from a normal distribution
random_2 = tf.random.Generator.from_seed(11)
random_2 = random_2.normal(shape=(3,2))

random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.27305737, -0.29925638],
        [-0.3652325 ,  0.61883307],
        [-1.0130816 ,  0.28291714]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

In [21]:
not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])

tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [23]:
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [ ]:
# seed can be set globally
rf.random.set_seed(42)

### Other ways to make tensors

In [24]:
tf.ones(shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [25]:
tf.zeros(shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [26]:
import numpy as np

numpy_A = np.arange(1, 25, dtype=np.int32)
A = tf.constant(numpy_A, shape=[2,4,3])
numpy_A, A

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32),
 <tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18],
         [19, 20, 21],
         [22, 23, 24]]], dtype=int32)>)

## Getting information from tensors (shape, rank, size)

In [27]:
rank_4_tensor = tf.zeros([2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [28]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [29]:
# Get various attributes of tensor
print("Datatype of every element: ", rank_4_tensor.dtype)
print("Number of dimensions (rank): ", rank_4_tensor.ndim)
print("Shape of tensor: ", rank_4_tensor.shape)
print("Elemens along axis 0 of tensor", rank_4_tensor.shape[0])
print("Elements along last axis of tensor: ", rank_4_tensor.shape[-1])
print("Total number of elements (2*3*4*5): ", tf.size(rank_4_tensor).numpy())

Datatype of every element:  <dtype: 'float32'>
Number of dimensions (rank):  4
Shape of tensor:  (2, 3, 4, 5)
Elemens along axis 0 of tensor 2
Elements along last axis of tensor:  5
Total number of elements (2*3*4*5):  120


In [30]:
# indexing tensors just like Python list
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [31]:
rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [32]:
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])

rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [33]:
rank_2_tensor[:1, :]

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[10,  7]], dtype=int32)>

In [34]:
rank_2_tensor[-1, :]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 4], dtype=int32)>

In [36]:
rank_2_tensor[0,:]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>

In [37]:
rank_2_tensor[:,0]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  3], dtype=int32)>

In [38]:
# Add an extra dimension (to the end)
# ... means all dimensions prior to
rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_2_tensor, rank_3_tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[10],
         [ 7]],
 
        [[ 3],
         [ 4]]], dtype=int32)>)

In [39]:
tf.expand_dims(rank_2_tensor, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [40]:
tf.expand_dims(rank_2_tensor, axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

## Manipulating tensors

In [41]:
tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10, tensor * 10, tensor - 10

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[20, 17],
        [13, 14]], dtype=int32)>, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[100,  70],
        [ 30,  40]], dtype=int32)>, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 0, -3],
        [-7, -6]], dtype=int32)>)

In [43]:
tf.math.add(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [44]:
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [45]:
# matrix multiplication tf.matmul
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [46]:
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [47]:
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

# Create another (3, 2) tensor
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

tf.reshape - allows us to reshape a tensor into defined shape

tf.transpose - switches the dimensions of a given tensor

In [48]:
tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [49]:
X @ tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [51]:
tf.transpose(X)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)>

In [52]:
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [53]:
tf.matmul(a=X, b=Y, transpose_a=True, transpose_b=False)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [56]:
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [57]:
tf.matmul(X, tf.transpose(Y)), tf.matmul(X, tf.reshape(Y, (2,3)))

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]], dtype=int32)>)

In [58]:
Y, tf.reshape(Y, (2,3)), tf.transpose(Y)

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  8,  9],
        [10, 11, 12]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  9, 11],
        [ 8, 10, 12]], dtype=int32)>)

### Changing the datatype of tensor

In [59]:
B = tf.constant([1.7,7.4])

C = tf.constant([1, 7])

B, C

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 7], dtype=int32)>)

In [60]:
B = tf.cast(B, dtype=tf.float16)
B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [62]:
C = tf.cast(C, dtype=tf.float32)
C

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 7.], dtype=float32)>

### Absolute values

In [63]:
D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [64]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

### Finding the min, max, mean, sum

In [65]:
E = tf.constant(np.random.randint(low=0, high=100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([70, 27, 23, 33, 92, 59, 92, 15, 71, 40, 78, 12, 65, 21, 47,  7, 93,
        8, 20, 69, 24, 60,  8, 88, 91, 53,  2, 58,  6, 54,  7, 13, 65, 72,
       80, 71, 54, 73, 12, 77, 72, 86, 25, 46, 83,  9, 75,  0, 38, 13])>

In [66]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [67]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=93>

In [68]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=47>

In [69]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2357>

In [74]:
Z = tf.cast(E, dtype=tf.float16)
tf.math.reduce_std(Z)

<tf.Tensor: shape=(), dtype=float16, numpy=29.92>

In [75]:
tf.math.reduce_variance(Z)

<tf.Tensor: shape=(), dtype=float16, numpy=895.5>

In [76]:
F = tf.constant(np.random.random(50))
F

<tf.Tensor: shape=(50,), dtype=float64, numpy=
array([0.39213323, 0.66244354, 0.82730395, 0.79680543, 0.19862137,
       0.92242452, 0.83404422, 0.83590018, 0.82119568, 0.03916684,
       0.02440617, 0.46728626, 0.10256014, 0.66698477, 0.19349752,
       0.76179413, 0.04261229, 0.4287241 , 0.39281716, 0.0215317 ,
       0.99050757, 0.39202897, 0.48109134, 0.61507659, 0.39689532,
       0.77203505, 0.17587066, 0.08407491, 0.11028248, 0.29335055,
       0.17656742, 0.6100726 , 0.99579464, 0.29066006, 0.79064254,
       0.17168706, 0.43066684, 0.59746443, 0.51712391, 0.13447978,
       0.60298507, 0.9096522 , 0.55791058, 0.23908183, 0.48071096,
       0.56611648, 0.21171773, 0.17241744, 0.17408719, 0.22098793])>

In [77]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=32>

In [78]:
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=19>

In [81]:
print(f"The maximum value of F is at position: {tf.argmax(F).numpy()}")
print(f"The maximum value of F is {tf.reduce_max(F).numpy()}")
print(f"Using tf.argmax() to index F, the maximum value is {F[tf.argmax(F)].numpy()}")
print(f"Are the two max values the same (they should be) {F[tf.argmax(F)].numpy() == tf.reduce_max(F).numpy()}")

The maximum value of F is at position: 32
The maximum value of F is 0.9957946429600089
Using tf.argmax() to index F, the maximum value is 0.9957946429600089
Are the two max values the same (they should be) True


### Squeezing a tensor

removing single-dimensions from a tensor

In [83]:
G = tf.constant(np.random.randint(0, 100, 50), shape=(1,1,1,1,50))
G.shape, G.ndim

(TensorShape([1, 1, 1, 1, 50]), 5)

In [84]:
G_squeezed = tf.squeeze(G)
G_squeezed.shape, G_squeezed.ndim

(TensorShape([50]), 1)

### One-hot encoding

In [85]:
some_list = [0, 1, 2, 3]
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [86]:
tf.one_hot(some_list, depth=4, on_value="We're live!", off_value="Offline")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b"We're live!", b'Offline', b'Offline', b'Offline'],
       [b'Offline', b"We're live!", b'Offline', b'Offline'],
       [b'Offline', b'Offline', b"We're live!", b'Offline'],
       [b'Offline', b'Offline', b'Offline', b"We're live!"]], dtype=object)>

### Squaring, log, squere root

In [87]:
H = tf.constant(np.arange(1,10))
H

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [88]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [91]:
#needs to be non integer
H = tf.cast(H, dtype=tf.float32)
tf.sqrt(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [92]:
# needs to be float
tf.math.log(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Manipulating tf.Variable tensor

assign()     - assign a different value to a particular index of a variable

add_assign() - add to an existing value and reassign it at a particular index of a tensor

In [94]:
I = tf.Variable(np.arange(0,5))
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([0, 1, 2, 3, 4])>

In [95]:
I.assign([0,1,2,3,50])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int64, numpy=array([ 0,  1,  2,  3, 50])>

In [96]:
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([ 0,  1,  2,  3, 50])>

In [97]:
I.assign_add([10,10,10,10,10])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int64, numpy=array([10, 11, 12, 13, 60])>

In [98]:
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([10, 11, 12, 13, 60])>

## Tensors and Numpy

np.array(tensor) and tensor.numpy() are valid expressions to switch between numpy array and tensor

In [99]:
J = tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [100]:
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [101]:
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [103]:
numpy_J = tf.constant(np.array([3.,7.,10.]))
tensor_J = tf.constant([3.,7.,10.])

numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

## Using @tf.function

In [104]:
# creating simple function
def f(x,y):
  return x ** 2 + y

x = tf.constant(np.arange(0,10))
y = tf.constant(np.arange(10,20))

f(x,y)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

In [105]:
# Create the same function and decore it with tf.function
# tf will tru to convert it into a faster version by making it part of computation graph
@tf.function
def tf_f(x,y):
  return x ** 2 + y

tf_f(x,y)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

## Finding access to GPUs

In [107]:
print(tf.config.list_physical_devices('GPU'))

[]


In [108]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



# Exercises

-Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().

-Find the shape, rank and size of the tensors you created in 1.

-Create two tensors containing random values between 0 and 1 with shape [5, 300].

-Multiply the two tensors you created in 3 using matrix multiplication.

-Multiply the two tensors you created in 3 using dot product.

-Create a tensor with random values between 0 and 1 with shape [224, 224, 3].

-Find the min and max values of the tensor you created in 6.

-Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].

-Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

-One-hot encode the tensor you created in 9.

## 1

In [141]:
scalar = tf.constant(7)
vector = tf.constant([1,2,3,4,5])
matrix = tf.constant([[1,2,3],[1,2,3]])
tensor = tf.constant([[1,2,3],[1,2,3],[1,2,3]])

In [142]:
scalar, vector, matrix, tensor

(<tf.Tensor: shape=(), dtype=int32, numpy=7>,
 <tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [1, 2, 3]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]], dtype=int32)>)

## 2

In [143]:
tensor.shape, tf.rank(tensor), tf.size(tensor)

(TensorShape([3, 3]),
 <tf.Tensor: shape=(), dtype=int32, numpy=2>,
 <tf.Tensor: shape=(), dtype=int32, numpy=9>)

## 3

In [115]:
tensor_one = tf.constant(np.random.rand(5,300))
tensor_two = tf.constant(np.random.rand(5,300))

In [116]:
tensor_one.shape, tensor_two.shape

(TensorShape([5, 300]), TensorShape([5, 300]))

## 4

In [117]:
tf.matmul(tensor_one, tf.transpose(tensor_two))

<tf.Tensor: shape=(5, 5), dtype=float64, numpy=
array([[75.0484178 , 75.0680739 , 76.6339016 , 78.701281  , 77.00747152],
       [73.00213106, 70.13234307, 70.99892083, 73.19960872, 71.28377251],
       [73.49832718, 71.71185672, 80.12794182, 74.25410496, 76.43754472],
       [77.96081697, 79.62694742, 76.12522885, 80.09394356, 81.97967505],
       [80.5527766 , 77.57436696, 82.24974354, 83.87080404, 81.33149455]])>

## 5

In [121]:
tf.tensordot(tensor_one, tf.transpose(tensor_two), axes=1)

<tf.Tensor: shape=(5, 5), dtype=float64, numpy=
array([[75.0484178 , 75.0680739 , 76.6339016 , 78.701281  , 77.00747152],
       [73.00213106, 70.13234307, 70.99892083, 73.19960872, 71.28377251],
       [73.49832718, 71.71185672, 80.12794182, 74.25410496, 76.43754472],
       [77.96081697, 79.62694742, 76.12522885, 80.09394356, 81.97967505],
       [80.5527766 , 77.57436696, 82.24974354, 83.87080404, 81.33149455]])>

## 6

In [126]:
tensor_three = tf.constant(np.random.rand(224,224,3))
tensor_three.shape

TensorShape([224, 224, 3])

## 7

In [127]:
tf.reduce_min(tensor_three).numpy(), tf.reduce_max(tensor_three).numpy()

(1.250064639135573e-06, 0.9999974789174587)

## 8

In [133]:
tensor_four = tf.constant(np.random.rand(1,224,224,3))
tensor_four, tensor_four.shape

(<tf.Tensor: shape=(1, 224, 224, 3), dtype=float64, numpy=
 array([[[[0.62858045, 0.86033878, 0.93924364],
          [0.79044621, 0.86030335, 0.84063256],
          [0.34138029, 0.99171688, 0.0690341 ],
          ...,
          [0.03946301, 0.04218008, 0.88561419],
          [0.00448878, 0.38101109, 0.1757498 ],
          [0.08979944, 0.38992136, 0.19356024]],
 
         [[0.48381937, 0.14948494, 0.33216822],
          [0.15719836, 0.13189074, 0.70261196],
          [0.6609272 , 0.19743275, 0.13673542],
          ...,
          [0.5036607 , 0.93992472, 0.59673213],
          [0.66205544, 0.51703624, 0.36447272],
          [0.26966678, 0.79761758, 0.26763432]],
 
         [[0.95296647, 0.52597607, 0.38903091],
          [0.7707324 , 0.60313478, 0.91234027],
          [0.4883951 , 0.51085116, 0.29344977],
          ...,
          [0.95261691, 0.37849286, 0.99582889],
          [0.24003538, 0.62608524, 0.04961063],
          [0.15814415, 0.25979433, 0.76163554]],
 
         ...,
 
       

In [134]:
tf.squeeze(tensor_four)

<tf.Tensor: shape=(224, 224, 3), dtype=float64, numpy=
array([[[0.62858045, 0.86033878, 0.93924364],
        [0.79044621, 0.86030335, 0.84063256],
        [0.34138029, 0.99171688, 0.0690341 ],
        ...,
        [0.03946301, 0.04218008, 0.88561419],
        [0.00448878, 0.38101109, 0.1757498 ],
        [0.08979944, 0.38992136, 0.19356024]],

       [[0.48381937, 0.14948494, 0.33216822],
        [0.15719836, 0.13189074, 0.70261196],
        [0.6609272 , 0.19743275, 0.13673542],
        ...,
        [0.5036607 , 0.93992472, 0.59673213],
        [0.66205544, 0.51703624, 0.36447272],
        [0.26966678, 0.79761758, 0.26763432]],

       [[0.95296647, 0.52597607, 0.38903091],
        [0.7707324 , 0.60313478, 0.91234027],
        [0.4883951 , 0.51085116, 0.29344977],
        ...,
        [0.95261691, 0.37849286, 0.99582889],
        [0.24003538, 0.62608524, 0.04961063],
        [0.15814415, 0.25979433, 0.76163554]],

       ...,

       [[0.41398141, 0.31440097, 0.30902231],
        [0.22

## 9

In [136]:
tensor = tf.constant([10,1,9,2,8,3,7,4,6,5])
tensor.shape

TensorShape([10])

In [137]:
tf.argmin(tensor), tf.argmax(tensor)

(<tf.Tensor: shape=(), dtype=int64, numpy=1>,
 <tf.Tensor: shape=(), dtype=int64, numpy=0>)

## 10

In [139]:
tf.one_hot(tensor, depth=10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.]], dtype=float32)>

# TODO: Extra-curriculum